version: '3.2'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - type: bind
        source: /home/foxmask/.config/joplin-desktop/database.sqlite
        target: /home/foxmask/.config/joplin-desktop/database.sqlite
    ports:
      - "8001:8001"
